import { MAX_IMPORT_BYTES, validateWorkspace } from "./model.js";
import { calculateScore, getEvidenceGap, getScoreBand, getScoreBreakdown } from "./scoring.js";

export function serializeWorkspace(workspace) {
  return `${JSON.stringify(validateWorkspace(workspace), null, 2)}\n`;
}

export function parseWorkspaceFile(text) {
  if (typeof text !== "string") {
    throw new TypeError("Import content must be text.");
  }
  const size = new TextEncoder().encode(text).length;
  if (size > MAX_IMPORT_BYTES) {
    throw new RangeError("Import file exceeds the 1 MiB limit.");
  }
  let parsed;
  try {
    parsed = JSON.parse(text);
  } catch {
    throw new SyntaxError("Import file is not valid JSON.");
  }
  return validateWorkspace(parsed);
}

export function safeFilename(value) {
  const normalized = String(value)
    .normalize("NFKD")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 60);
  return normalized || "idea";
}

function escapeMarkdown(value) {
  return String(value).replace(/([\\`*_{}\[\]()#+.!|>-])/g, "\\$1");
}

export function buildResearchBrief(idea) {
  const score = calculateScore(idea.scores);
  const band = getScoreBand(score);
  const breakdown = getScoreBreakdown(idea.scores);
  const evidence = idea.evidence.length
    ? idea.evidence.map((item) => `- **${escapeMarkdown(item.source)}** (${item.strength}, ${item.observedAt}): ${escapeMarkdown(item.observation)}`).join("\n")
    : "- No evidence recorded yet.";
  const scoreRows = breakdown
    .map((factor) => `| ${factor.label} | ${factor.value}/5 | ${Math.round(factor.weight * 100)}% | ${factor.contribution} |`)
    .join("\n");

  return `# ${escapeMarkdown(idea.title)} — Opportunity Brief

## Problem

${escapeMarkdown(idea.problem)}

## Audience and context

- **Audience:** ${escapeMarkdown(idea.audience)}
- **Context:** ${escapeMarkdown(idea.context || "Not recorded")}
- **Lifecycle:** ${escapeMarkdown(idea.status)}

## Proposed outcome

${escapeMarkdown(idea.outcome)}

## Opportunity score

**${score}/100 — ${band.label}.** This prioritization score is not proof of market demand.

| Factor | Value | Weight | Contribution |
| --- | ---: | ---: | ---: |
${scoreRows}

## Evidence

${evidence}

## Evidence gap

${escapeMarkdown(getEvidenceGap(idea))}

## Next validation step

${escapeMarkdown(idea.nextStep || "Define the smallest action that can reduce the largest assumption.")}

## Assumptions to challenge

- The observed problem is frequent and costly enough to change behavior.
- The target audience is reachable.
- The proposed outcome is meaningfully better than current alternatives.
- A useful first version is feasible with available resources.

---

Generated by AI Idea Hunter from user-entered data. Verify every claim before sharing.
`;
}

export function downloadText(filename, text, type = "text/plain;charset=utf-8") {
  const blob = new Blob([text], { type });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  anchor.hidden = true;
  document.body.append(anchor);
  anchor.click();
  anchor.remove();
  setTimeout(() => URL.revokeObjectURL(url), 0);
}
